spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_pulse?createDatabaseIfNotExist=true
    username: root
    password: Saikat12345
  jpa:
    hibernate:
      ddl-auto: update  # <--- CHANGE THIS BACK NOW
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080